# Day 1 

In [8]:
list=["one","two"]
for j in list:
    print(j)

one
two


In [10]:
def hello():
    print("Hello")
hello()

Hello


In [25]:
def name(arg):
    print("Hi",arg)
a=input()
name(a)

test
Hi test


In [28]:
def change_list(list11):
    list11.append(20)
    print(list11)
list11=[10,15]
change_list(list11)
print(list11)

[10, 15, 20]
[10, 15, 20]


In [31]:
import datetime
from datetime import date
import calendar
today=datetime.date.today()
print(today)
print(today.day)
print(today.year)
print(today.month)

2019-06-25
25
2019
6


In [38]:
a = date(2019,1,8)
b = date(2019,12,31)
print(b-a)

357 days, 0:00:00


In [35]:
print(date.today())

2019-06-25


In [39]:
print(calendar)

<module 'calendar' from 'C:\\Users\\Gcelt\\Anaconda3\\lib\\calendar.py'>


In [93]:
#1)Write a function which accepts string param and returns reverse
def reverse_str(arg):
#     i=len(arg)
#     for b in arg:
#         print(arg[i-1])
#         i-=1
    return arg[::-1]
reverse_str("Hello")

'olleH'

In [95]:
#2)Function which accepts any arguement and returns if palindrome or not, then do it with recursion
def check_pal(arg):
        rev=reverse_str(arg)
        if arg==rev:
            print("Palindrome")
        else:
            print("!Palindrome")
def reverse_str(arg):
    return arg[::-1]
    
            
check_pal("121")


!Palindrome


In [91]:
nums = [1,2,3,4]
for i in nums:
    print(i)
nums1=nums.copy()
print(nums1)
nums.clear()
print(nums)
nums.append(5)
print(nums)

1
2
3
4
[1, 2, 3, 4]
[]
[5]


In [2]:
import numpy as np
print (np.__version__)
z = np.arange(1,10)
print(z[::-1])
y = np.arange(9).reshape(3,3)
print(y)

1.16.2
[9 8 7 6 5 4 3 2 1]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [126]:
def sel_sort(x):
    for i in range(len(x)):
        swap= i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return xi
x=np.array([2,1,4,3,5])
sel_sort(x)

array([2, 5, 4, 4, 5])

In [125]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [132]:
def sel_sort(x):
    for i in range(len(x)):
        swap= i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x
# x=np.array([2,1,4,3,5])
x=(np.random.randint(low=1, high=50, size=4))
sel_sort(x)

array([13, 17, 34, 44])