# Day 1 

### List
List is a non homogeneous container data type, its elements are comma `,` seperated.

In [8]:
# Define a list
list=["one","two"]
# Iterates through all elements of the list
for j in list:
    print(j)

one
two


### Functions
Function are reusable blocks of code, they are declared using the `def` keyword.

In [10]:
def hello():
    print("Hello")
hello()

Hello


In [25]:
def name(arg):
    print("Hi",arg)
a=input() 
name(a)

test
Hi test


In [28]:
def change_list(list11):
    # Adds 20 to the list
    list11.append(20)
    print(list11)
list11=[10,15]
change_list(list11)
print(list11)

[10, 15, 20]
[10, 15, 20]


External libraries and modules can be used in python using the `import` and `from` keyword.
They can also be aliased using the `as` keyword.

In [2]:
import datetime
from datetime import date
import calendar
today=datetime.date.today()
print(today)
print(today.day)
print(today.year)
print(today.month)

2019-07-02
2
2019
7


In [38]:
a = date(2019,1,8)
b = date(2019,12,31)
print(b-a)

357 days, 0:00:00


In [35]:
print(date.today())

2019-06-25


In [3]:
print(calendar)

<module 'calendar' from '/usr/lib/python3.7/calendar.py'>


In [4]:
# A function which accepts string param and returns reverse
def reverse_str(arg):
#     i=len(arg)
#     for b in arg:
#         print(arg[i-1])
#         i-=1
    return arg[::-1]
reverse_str("Hello")

'olleH'

In [5]:
# Function which accepts any arguement and returns if palindrome or not
def check_pal(arg):
        rev=reverse_str(arg)
        if arg==rev:
            print("Palindrome")
        else:
            print("!Palindrome")
check_pal("121")

Palindrome


In [8]:
nums = [1,2,3,4]
nums1=nums.copy() # Creates copy of list
print(nums1)
nums1.clear() # Clears list elements
print(nums1)

[1, 2, 3, 4]
[]


In [10]:
import numpy as np
print (np.__version__)
z = np.arange(1,10)
print(z)
y = np.arange(9).reshape(3,3) # reshapes the created list
print(y)

1.16.4
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [125]:
Z = np.zeros(10) # Creates list of zeroes
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
# Creates a random list and sorts its elements
def sel_sort(x):
    for i in range(len(x)):
        swap= i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

x=(np.random.randint(low=1, high=50, size=4)) # Generates a list of random elements
print(x)
sel_sort(x)

[23 36 20 49]


array([20, 23, 36, 49])